### ISSUE TITLE
Question about library

### ISSUE THREAD

**Issue by Noravorn2546** [GrapesGoober/RSA-App#31]
I have a problem with the code unable to find `from cryptography.fernet import Fernet` which make the code unable to run

**Comment by GrapesGoober** [comment]
Oh yea right, I'm using crypto library. Run `pip install cryptography`

**Comment by GrapesGoober** [comment]
Note that for `Develop-Authentication` branch, I goofed around with the channel a bit. There's some problems
# Your Problem
I'm not sure what the classes and functions are gunna be like, so it might be prone to change. Ideally, I should let you use the code from the `main` branch, but that is really hard to implement authentication into
# My Problem
The logic for handling authentication requires lots of duplicate code & internal state. Ideally I should create either
- one super class called `Channel`, where `Receiver` and `Sender` inherits from
- or, create just one class `Channel`, where it can act like both receiver and sender.

I decided to go for the second option, since I think that is simpler. Sending and receiving both uses very similar code, afterall. However, I'm not sure if you're gunna find it too hard to read and understand. If you have issues with this you can talk to me more about it because I think it's quite ugly code at the moment

**Comment by GrapesGoober** [comment]
# FYI
If you're okay with the dependency problem, then you can close this issue right away
